name: CI
env: 
  url: 'http://devinhouse.com'

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '**/*.md'
  pull_request:
      branches: [main]
  
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      
      - name: Build
        run: echo Hello World!
      
      - name: Rodar testes
        run: echo Rodar testes
        
  deploydev:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: Deploy em dev
        run: echo Deploy em dev ${{secrets.URL_BD}} - ${{env.url}}
        
  deployqa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy em qa
        run: echo Deploy em qa

  deployprod:
    needs: [deployqa, deploydev]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy em prod
        run: echo Deploy em prod        
