name: CI

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '**/*.md'
  pull_request:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      
      - name: Run hello world
        run: echo Hello World!
      
      - name: Rodar testes
        run: echo Rodar testes
        
